// UPON A NEW YEAR, UPDATE THIS FILE TO INCLUDE THE NEW YEAR IN THE SCHOOL_YEARS ARRAY AND SET IT AS THE DEFAULT_SCHOOL_YEAR
// USE 2024-25 AS TESTING YEAR, NO DATA IS THERE FOR THAT YEAR

export const SCHOOL_YEARS = ["2026-27", "2025-26", "2024-25"] as const;

export type SchoolYear = (typeof SCHOOL_YEARS)[number];

export const DEFAULT_SCHOOL_YEAR: SchoolYear = SCHOOL_YEARS[0];
